### ISSUE TITLE
Micro pcf's cert blocks cloudfoundry Java client library

### ISSUE THREAD

**Issue by gregturn** [pivotal-cf/micropcf#11]
The cert served breaks cloudfoundry-java-lib:

```
org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://api.local.micropcf.io/info":Certificate for <api.local.micropcf.io> doesn't contain CN or DNS subjectAlt; nested exception is javax.net.ssl.SSLException: Certificate for <api.local.micropcf.io> doesn't contain CN or DNS subjectAlt
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:580)
	at org.cloudfoundry.client.lib.rest.LoggingRestTemplate.doExecute(LoggingRestTemplate.java:54)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:530)
	at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:237)
```

This call has the self signed cert check disabled so this is something else. I'm hoping that mending the cert is all it takes to connect through our standard library.

**Comment by sclevine** [comment]
Fixed by e4aeaca26d70918f88ab264c8e82452025a0c1b1.

(Leaving this issue open until we have a nightly build available.)

**Comment by gregturn** [comment]
:+1:

**Comment by davidwadden** [comment]
@gregturn - our latest nightly builds are available at https://micropcf.s3.amazonaws.com/nightly/index.html.  this fix should be available in the builders newer than **v0.3.0-13-ge4aeaca**

please re-open if this doesn't resolve your issues

thanks!
david

**Comment by gregturn** [comment]
:+1:

**Comment by gregturn** [comment]
Verified this definitely now works. Thanks!
