### ISSUE TITLE
Question: Does micropcf include the PCF apps manager?

### ISSUE THREAD

**Issue by blinse** [pivotal-cf/micropcf#12]
First of all, thanks for providing microPcf. It is very easy to install and seems like a great starting point. 

Yet I have a couple of questions:

1) Does it include the Apps manager, that is provided in ordinary PCF installations? If yes, how do I access it?
2) What is the difference to bosh-lite? This is the local cloudfoundry installation I was working previously with.
3) What is the cloudfoundry version it provides? Is the current version already running diego?

Would it make sense to answer those questions in a FAQ in the Wiki. If yes, I would be glad to put it there.

Thanks!

**Comment by jbayer** [comment]
_1) Does it include the Apps manager, that is provided in ordinary PCF installations? If yes, how do I access it?_

MicroPCF does not yet include Apps Manager. we do intend to add it as an option. @davidwadden may choose to use this issue to track that.

_2) What is the difference to bosh-lite? This is the local cloudfoundry installation I was working previously with._

MicroPCF does not require you to know anything about BOSH to get a full CF installation up and running. the MicroPCF configuration leverages BOSH to create the monit processes inside the VM. in the future, we hope to expose a BOSH option to MicroPCF for users that may want to graduate to using BOSH.

_3) What is the cloudfoundry version it provides? Is the current version already running diego?_

currently MicroPCF is built with one of the very latest versions of cf-release. yes it is already using diego. in the future, we are planning for the default MicroPCF experience to track the Pivotal Cloud Foundry (PCF) releases for parity. one of the builds may also keep tracking the latest cf-releases as well, that remains to be determined.

**Comment by blinse** [comment]
Hi James, 

thanks for the answers. This is very helpful. 

Benedikt
