### ISSUE TITLE
How to update the default DNS server config?

### ISSUE THREAD

**Issue by dwu-pivotal** [pivotal-cf/micropcf#14]
I'd like to put my micropcf on my laptop, and I may need to demo to my customer in some place with no external network access, so the default 8.8.8.8 may not work.

**Comment by davidwadden** [comment]
we plan supporting running microPCF in an offline configuration at some point in the near future, but we haven't prioritized supporting that just yet.  if you're interested in experimenting on your own, i think you may be able to run a version of [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) on your host that handles this.

i'm curious where you get `8.8.8.8` from.  i checked my `/etc/resolv.conf` running using VMware Fusion:

```
○ → vagrant ssh -c "cat /etc/resolv.conf"
nameserver 127.0.0.1
nameserver 172.16.139.2
search localdomain
Connection to 172.16.139.204 closed.
```

Which looks like after the consul DNS server, it goes to the host IP on the NAT interface (basically delegates to the Host to perform the DNS lookup).  Is that where you have `8.8.8.8` configured as your DNS?  This is where I think you could slip in DNSMasq as a custom resolver on the host to handle resolution for the `local.micropcf.io` subdomain.

**Comment by dwu-pivotal** [comment]
Do you mean our script copy from the host's resolv.conf, and write to the vagrant VM? Let me have a try on this. thx

**Comment by sclevine** [comment]
Doing that would break microPCF by preventing services inside of it from finding each other.

David is saying that `*.local.micropcf.io` needs to resolve to `192.168.11.11` on the host machine for microPCF to work properly. One way to accomplish this is by running [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) on the host to create a wildcard CNAME record. See [here](http://stackoverflow.com/questions/22313142/wildcard-subdomains-with-dnsmasq).

**Comment by dwu-pivotal** [comment]
Thx. But my /etc/resolv.conf in both vagrant vm, and app contriner is 
nameserver 127.0.0.1
nameserver 8.8.8.8
nameserver 10.0.2.2
How can I change that to point to my host dnsmasq?

**Comment by sclevine** [comment]
`10.0.2.2` is the host address, so your microPCF `resolv.conf` is already configured to query port 53 on the host. Running dnsmasq on port 53 with the configuration described above may just work.

**Comment by dwu-pivotal** [comment]
Change my resolv.conf to (dnsmasq before 8.8.8.8)
nameserver 127.0.0.1
nameserver 8.8.8.8,
bring vagrant up, the result in vagrant vm become 
nameserver 127.0.0.1
nameserver 10.0.2.2
nameserver 8.8.8.8

Perfect. Thx Stephen!
