### ISSUE TITLE
Upon restart of the host, vagrant fails to bring micropcf back up

### ISSUE THREAD

**Issue by melofred** [pivotal-cf/micropcf#15]
Upon restart of the host, vagrant fails to bring micropcf back up and a full reprovision (vagrant destroy / vagrant up) is necessary.  
Upon restart of the host,  cf target will fail, with the CC rest services down. "vagrant up" claims the machine is already up and running, and "vagrant reload" won't help either.

**Comment by davidwadden** [comment]
fred,

please download one of our latest nightly builds at https://micropcf.s3.amazonaws.com/nightly/index.html and try again.  we've made a lot of changes around provisioning and it's a lot more reliable now.

if you still have issues, please give us a rundown of the commands you issued so we can attempt to reproduce.  there's some places vagrant needs to be invoke the service startup and a `sudo reboot` from within an `vagrant ssh` terminal might not restart the services.

thanks,
david

**Comment by davidwadden** [comment]
this should be fixed with [v0.4.0](https://github.com/pivotal-cf/micropcf/releases/tag/v0.4.0) release.  

note that logging onto the micropcf vm directly and issuing a `reboot` won't work, please use vagrant up/halt/reload as you mentioned doing

**Comment by melofred** [comment]
Thanks David.. we'll give it a try tonight and let you know! I appreciate the follow-up.

**Comment by melofred** [comment]
@davidwadden  seems to be fine now. Thanks for this!
