### ISSUE TITLE
Trying to vagrant up on AWS

### ISSUE THREAD

**Issue by omearaj** [pivotal-cf/micropcf#17]
I'm getting the error below when I try to vagrant up on AWS. I can vagrant SSH into the VM and I have 386 processes running. When I try to cf api --skip-ssl-validation http://Ext.IP.xip.io I get a 404 not found error. Ideas or log files to review? 

Bringing machine 'default' up with 'aws' provider...
==> default: Checking if box 'micropcf/base' is up to date...
==> default: Warning! The AWS provider doesn't support any of the Vagrant
==> default: high-level network configurations (`config.vm.network`). They
==> default: will be silently ignored.
==> default: Launching an instance with the following settings...
==> default:  -- Type: m4.large
==> default:  -- AMI: ami-1712467d
==> default:  -- Region: us-east-1
==> default:  -- Keypair: vagrant
==> default:  -- Block Device Mapping: []
==> default:  -- Terminate On Shutdown: false
==> default:  -- Monitoring: false
==> default:  -- EBS optimized: true
==> default:  -- Source Destination check: 
==> default:  -- Assigning a public IP address in a VPC: false
==> default:  -- VPC tenancy specification: default
==> default: Waiting for instance to become "ready"...
==> default: Waiting for SSH to become available...
==> default: Machine is booted and ready for use!
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default:  
==> default:  
==> default: %
==> default:  
==> default: T
==> default: o
==> default: t
==> default: a
==> default: l
==> default:  
==> default:  
==> default:  
==> default:  
==> default: %
==> default:  
==> default: R
==> default: e
==> default: c
==> default: e
==> default: i
==> default: v
==> default: e
==> default: d
==> default:  
==> default: %
==> default:  
==> default: X
==> default: f
==> default: e
==> default: r
==> default: d
==> default:  
==> default:  
==> default: A
==> default: v
==> default: e
==> default: r
==> default: a
==> default: g
==> default: e
==> default:  
==> default: S
==> default: p
==> default: e
==> default: e
==> default: d
==> default:  
==> default:  
==> default:  
==> default: T
==> default: i
==> default: m
==> default: e
==> default:  
==> default:  
==> default:  
==> default:  
==> default: T
==> default: i
==> default: m
==> default: e
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: T
==> default: i
==> default: m
==> default: e
==> default:  
==> default:  
==> default: C
==> default: u
==> default: r
==> default: r
==> default: e
==> default: n
==> default: t
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: D
==> default: l
==> default: o
==> default: a
==> default: d
==> default:  
==> default:  
==> default: U
==> default: p
==> default: l
==> default: o
==> default: a
==> default: d
==> default:  
==> default:  
==> default:  
==> default: T
==> default: o
==> default: t
==> default: a
==> default: l
==> default:  
==> default:  
==> default:  
==> default: S
==> default: p
==> default: e
==> default: n
==> default: t
==> default:  
==> default:  
==> default:  
==> default:  
==> default: L
==> default: e
==> default: f
==> default: t
==> default:  
==> default:  
==> default: S
==> default: p
==> default: e
==> default: e
==> default: d
==> default:  
==> default:  
==> default: 0
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
==> default:  
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default:  
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default:  
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default: :
==> default: -
==> default: -
==> default:  
==> default:  
==> default:  
==> default:  
==> default:  
==> default: 0
100    13  100    13    0  
==> default:    0   3869      0 --
==> default: :--:-- --:--:-
==> default: - --:--:--
==> default:   4333
==> default: Waiting for services to start...
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by omearaj** [comment]
BTW, this same Vagrantfile worked running it locally on virtualbox

**Comment by sclevine** [comment]
Hi @omearaj,

Are you still experiencing this issue with [0.4.0](https://github.com/pivotal-cf/micropcf/releases/download/v0.4.0/Vagrantfile-v0.4.0.base)?

**Comment by omearaj** [comment]
@sclevine - Its been running for about 3 hours and showing the message below. I'm able to target the api and login but pushing a simple spring application fails this: 

When I try to start the app I get a staging error.

reating app next in org micropcf-org / space mpcf-space as admin...
OK

Creating route next.54.165.43.103.xip.io...
OK

Binding next.54.165.43.103.xip.io to next...
OK

Uploading next...
Uploading app files from: target/scale-1.0.0-BUILD-SNAPSHOT.war
Uploading 6.2M, 59 files
Done uploading               
OK

timeout connecting to log server, no log will be shown
Starting app next in org micropcf-org / space mpcf-space as admin...
FAILED
Error performing request: Get http://api.54.165.43.103.xip.io/v2/apps/07c472f3-ca2c-4e6a-b086-ff708626a891: dial tcp: lookup api.54.165.43.103.xip.io: no such host


### This is the message from the vagrant up on AWS

==> default: Box 'micropcf/base' could not be found. Attempting to find and install...
    default: Box Provider: aws
    default: Box Version: 0.24.0
==> default: Loading metadata for box 'micropcf/base'
    default: URL: https://atlas.hashicorp.com/micropcf/base
==> default: Adding box 'micropcf/base' (v0.24.0) for provider: aws
    default: Downloading: https://atlas.hashicorp.com/micropcf/boxes/base/versions/0.24.0/providers/aws.box
==> default: Successfully added box 'micropcf/base' (v0.24.0) for 'aws'!
==> default: Checking if box 'micropcf/base' is up to date...
==> default: Warning! The AWS provider doesn't support any of the Vagrant
==> default: high-level network configurations (`config.vm.network`). They
==> default: will be silently ignored.
==> default: Launching an instance with the following settings...
==> default:  -- Type: m4.large
==> default:  -- AMI: ami-71510f1b
==> default:  -- Region: us-east-1
==> default:  -- Keypair: vagrant
==> default:  -- Block Device Mapping: []
==> default:  -- Terminate On Shutdown: false
==> default:  -- Monitoring: false
==> default:  -- EBS optimized: true
==> default:  -- Source Destination check: 
==> default:  -- Assigning a public IP address in a VPC: false
==> default:  -- VPC tenancy specification: default
==> default: Waiting for instance to become "ready"...
==> default: Waiting for SSH to become available...
==> default: Machine is booted and ready for use!
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default: Waiting for services to start...

**Comment by davidwadden** [comment]
This looks like an issue with `xip.io` resolution.  We have a couple of known issues (reported on our [releases](https://github.com/pivotal-cf/micropcf/releases) page)  with AWS (xip.io flakiness and EBS base storage can't handle `cf push`).  We recommend either using VirtualBox or VMware at this point in time, we're still working on making AWS more reliable and more performant.

**Comment by omearaj** [comment]
Thanks @davidwadden I'll try AWS in a future release. It did work on virtualbox locally.

**Comment by vatsan** [comment]
I am stuck on the "default: Waiting for services to start..." message as well. I am using VirtualBox on a Mac. Any pointers? It's been stuck for over 2 hours now!

**Comment by debu66er** [comment]
@vatsan are you connected to Internet? When I try to start MicroPCF connectivity I get stuck where you are now. Just guessing if it is your same case...

**Comment by davidwadden** [comment]
i'm going to close this issue as we're planning to revisit AWS in the future and it's not being supported in the initial release.  we haven't had luck getting the I/O throughput necessary to have CF operate in a stable manner.

@vatsan we can discuss the issues you're seeing on #26 
@debu66er can you open a new issue and give us details on what version you're running and your configuration?  that `Waiting for services to start...` message will hang indefinitely if the cluster fails to start properly
