### ISSUE TITLE
Enable Google vagrant provider for deploy to Google Cloud Platform

### ISSUE THREAD

**Issue by hostirosti** [pivotal-cf/micropcf#18]
Hi,

I'm working on enabling micropcf to be deployed to Google Cloud Platfrom. The Vagrantfile part is almost done. Who can help / whom can I contact for creating a micropcf/base GCP image?

**Comment by davidwadden** [comment]
Please contact me at dwadden@pivotal.io, I'm the product manager for MicroPCF and would be happy to discuss this further with you.

**Comment by omearaj** [comment]
@hostirosti _ I'm interested in using this when you get it work. Please let me know, thanks

**Comment by hostirosti** [comment]
@davidwadden _ David, have you received my email?

**Comment by davidwadden** [comment]
Closing this issue.  We're not targeting Cloud platforms with the initial release.
