### ISSUE TITLE
MICRO_PCF_ON_WINDOWS

### ISSUE THREAD

**Issue by parthitheindian** [pivotal-cf/micropcf#20]
Hello All,
              Its great to have the Running Cloud version on our Laptop. Great work. Will these Micro PCF can we try installing on Windows? Am seeing everybody is trying it on Linux or Mac only. Can anyone clarify on this, also share the working steps for Windows too. Thanks.

**Comment by davidwadden** [comment]
MicroPCF works on Windows.  It is still a Linux cluster behind the scenes so doesn't support things like .NET.  But it should be possible to `vagrant up` on a Windows host and use the Windows version of the `cf` utility to manage it.

It should be the same steps, download a `Vagrantfile` from the [releases](https://github.com/pivotal-cf/micropcf/releases) page and `vagrant up` accordingly.  I'll work on improving the documentation to make it clear that Windows is supported.

**Comment by parthitheindian** [comment]
Yes, we are eagerly waiting for the Windows Installation Documentation. We tried by downloading the Vagrantfile, but its throwing some errors.

**Comment by pradp** [comment]
I don't see any issues with windows installation. It works perfectly fine in my windows 7.

**Comment by debu66er** [comment]
It also works for me on Windows 7, Vagrant 1.8.1, VirtualBox 5.0.14 and MicroPCF 0.5.0

**Comment by sclevine** [comment]
@parthitheindian Are you still having issues with MicroPCF on Windows, or can I close this issue?

**Comment by davidwadden** [comment]
MicroPCF works fine on Windows.  Closing issue.
