### ISSUE TITLE
Question: can I use uaac with micropcf for registering new clients?

### ISSUE THREAD

**Issue by 1123** [pivotal-cf/micropcf#23]
I am trying to do: uaac token client get admin

such that I can subsequently register a new client with the uaa. What is the password? 

Or is there a different way to register new uaa clients?

The application should be able manage additional information for the CF user.

**Comment by sclevine** [comment]
The client secret for the admin client is `admin-client-secret`.

See the UAA client definitions in the [MicroPCF deployment manifest](https://github.com/pivotal-cf/micropcf/blob/e8458643ab0945cfc969aac30c89fa45bfa7cf17/images/manifest.yml#L310).

**Comment by keaty** [comment]
Closing. Feel free to re-open if this does not answer your question.

**Comment by blinse** [comment]
Thanks! Very helpful.
