### ISSUE TITLE
security-group for specific access

### ISSUE THREAD

**Issue by myminseok** [pivotal-cf/micropcf#28]
Hello,

I tried to  access external DB(192.168.67.2:3306)  from container,
but security-group is not working that i expected.
this is how  to reproduce:

env: micropcf base 0.28.0

1)  sshed into micropcf(192.168.11.11) and set iptables:
iptables -A INPUT -p tcp -m tcp --dport 3306 -j ACCEPT
iptables -t nat -A PREROUTING  -d 192.168.11.11 -p tcp --dport 3306 -j DNAT --to-destination 192.168.67.2:3306
iptables -t nat -A POSTROUTING -j MASQUERADE

2)  I set security group as following, but not working
[{"protocol":"tcp","destination":"192.168.11.0/24","ports":"3306"}]
cf create-security-group mysql mysql-sg
cf bind-security-group mysql micropcf-org micropcf-space
cf bind-staging-security-group mysql
cf bind-running-security-group  mysql

alternatively if I set all_open security group then it works, ( which is the same with PCF default security group)
[{"destination": "0.0.0.0-255.255.255.255","protocol": "all"}]

thanks.

**Comment by sclevine** [comment]
Hi @myminseok,

You should be able to access 192.168.11.11 from an app container without any additional security groups. Only outbound connections (for instance, to the host: 192.168.11.1) require security groups.

I'm unsure if your iptables changes will play nicely with the existing iptables rules. If you need to access port 3306 on another machine in your network, I suggest you add a security group allowing access to that machine directly:
```
[{"protocol":"tcp","destination":"192.168.67.2","ports":"3306"}]
```

If you must forward connections to that machine, I suggest you handle that on your host system (either via SSH forwarding, or [iptables rules](http://serverfault.com/questions/586486/how-to-do-the-port-forwarding-from-one-ip-to-another-ip-in-same-network).

**Comment by sclevine** [comment]
Closing. Feel free to re-open if you still have questions.
