### ISSUE TITLE
Future of micropcf: Docker, Otto, Docker Vagrant provider?

### ISSUE THREAD

**Issue by SamuelMarks** [pivotal-cf/micropcf#30]
**Discussion thread**
MicroPCF seems to be a great project for getting a development environment up and running moderately quickly.

Currently I am using bosh-lite, where I had to buy an extra 8GB of RAM, and then it only took ~90 minutes to install everything (cf v230 and diego). The VM allocated 6144MB of memory for itself, and 4 CPUs. I note that your Vagrantfile uses 25% of host memory, and all CPUs.

In production deployments there's a multitude of specialised nodes.

_Why don't we make our dev install micro-service orientated?_

**Options**
Here are the primary options I can think of, add yours if its not below:

  - An 'ocean' of `Dockerfile`s, orchestrated trivially (we're talking one host afterall)
  - [Otto](https://www.ottoproject.io) (Hashicorp's Vagrant successor; uses Vagrant beneath-the-scenes)
  - [Vagrant providers](https://www.vagrantup.com/docs/providers) (includes Docker)

**Disadvantages**

  - Different to current approach
  - Development required

**Advantages**

  - Easier to isolate and test individually, and progressively test with more dependent components
  - Less system overhead
  - Smaller file-size (great for sharing 'snapshots' across development teams)

**Comment by sclevine** [comment]
Hi @SamuelMarks, thanks for the feedback!

The goal of MicroPCF is to mimic the functionality of a full PCF installation locally with some assurance that apps developed using MicroPCF will run the same way when pushed to production (PCF). We've put a lot of thought into the current implementation of MicroPCF, and we believe that it best serves this goal. Most importantly, the current implementation allows us to directly consume the BOSH releases for the various CF components and service brokers that we depend on.

Here are what I would consider to be disadvantages of splitting MicroPCF into Docker images:

- **Slight increase in overhead (for most users)**

  Most of our users run OS X or Windows on their workstations. Docker containers must be run in an extra VM running the docker daemon on these platforms.

- **More complex installation**

  We currently depend on Virtualbox and Vagrant to run MicroPCF. We believe that this is simple and familiar for many of our users.

- **More complex build process / more work to bump BOSH release versions**

  We currently use bosh-provisioner with a single BOSH deployment manifest to do a pseudo-bosh-deploy of the BOSH releases we depend on. Breaking the individual components into containers would either require a different deployment manifest for each component, or a move to real BOSH with extra tooling to create images. In short, it's more complicated and likely more work for us when we want to bump versions.

- **Questionable benefit for testing**

  Each component we integrate is already unit tested and acceptance tested by the teams that develop those components. We run the acceptance test suites from each component against MicroPCF to validate that MicroPCF deploys and configures them appropriately.

  Many of these acceptance tests require a full CF deployment to run. Breaking MicroPCF down into smaller components might allow us leave off a few components in each test (at the expense of risking components breaking each other) but I suspect the benefit would be marginal.

To address your other suggestions: using the Vagrant Docker provider would require the user to install Virtualbox, Docker, and Vagrant. Using multiple VMs for MicroPCF (with Otto, or just using Vagrant) would increase the footprint very significantly.

While I agree that a more modular, lower footprint method of developing apps for CF would be neat, the current implementation is more in line with our goals.

**Comment by SamuelMarks** [comment]
Thanks @sclevine for your detailed reply,

You bring up some good points, I'm thinking the best way to approach this is to make production CF deployable in containers, then revisit the concept.
