### ISSUE TITLE
Naming question?

### ISSUE THREAD

**Issue by mcowger** [pivotal-cf/micropcf#6]
The name of the project is MicroPCF, implying, at least to me, that this is based on and an example of PCF, or Pivotal's version of Cloud Foundry.

However, looking through the build and other sources, it appears to be standard opensource-based CF.  

So, is it based on PCF and I've missed it?  Or is the name implying something incorrect?

--M

**Comment by jbayer** [comment]
MicroPCF is in it's infancy. in addition to it being the easiest way to get a full OSS CF installation on a local developer machine, we also want to make it the best way to onramp to other related pivotal technologies like a apps manager (the developer facing web UI) and spring technologies like spring boot, spring cloud and spring cloud data flow.

**Comment by mcowger** [comment]
Gotcha - so it's so simply too early to see the pivotal parts.   Thanks for the clarification.
